version: '3.8'

services:
  react-dev:
    build: .
    container_name: react-dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
